//! Stage 4 — emit Rust source from resolved specs.

use std::collections::BTreeSet;

use crate::emit_drivers::{driver, DriverCtx};
use crate::registry::Registry;
use crate::resolve::{resolve, Resolved};
use crate::spec::SpecNode;

/// Where the emitted code finds the runtime ABI. `avb_abi` in the prototype;
/// in the real repo this is split (`array_vis_bench_core::bench_registry` for
/// `AlgorithmEntry`/`ALGORITHMS`/`RunConfig`, `…_traits` for the traits) — when
/// porting, the entry template's `{abi}::` prefixes become those real paths.
#[derive(Debug, Clone)]
pub struct EmitConfig {
    pub abi: String,
}
impl Default for EmitConfig {
    fn default() -> Self {
        EmitConfig { abi: "avb_abi".to_string() }
    }
}

fn use_lines(uses: &[String], indent: &str) -> String {
    uses.iter().map(|u| format!("{indent}use {u};\n")).collect()
}

/// One spec → a named type alias + derived label + dispatch fn. Each sort's
/// imports are scoped inside its own private module, so two invocations whose
/// `uses` overlap don't collide at crate scope (a real hazard — duplicate
/// `use` at module scope is a compile error). The public names are re-exported.
pub fn emit_one(alias: &str, r: &Resolved) -> String {
    format!(
        "#[allow(non_snake_case)]\n\
         mod __{alias}_impl {{\n\
         \x20   #[allow(unused_imports)] use super::*;\n{uses}\
         \x20   pub type Ty = {ty};\n\
         \x20   pub const NAME: &str = {label:?};\n\
         \x20   pub fn run(arr: &mut [usize]) {{ <Ty>::sort(arr); }}\n\
         }}\n\
         pub use __{alias}_impl::Ty as {alias};\n\
         #[allow(non_upper_case_globals)] pub use __{alias}_impl::NAME as {alias}_NAME;\n\
         #[allow(non_snake_case)] pub use __{alias}_impl::run as {alias}_run;\n",
        uses = use_lines(&r.uses, "    "),
        ty = r.type_expr,
        label = r.label,
    )
}

/// Many specs → one module with a `SORTS` dispatch table. The union of every
/// variant's imports is emitted once at the top (deduped), so the table needs
/// no per-row scoping.
pub fn generate_table(reg: &Registry, specs: &[SpecNode], module: &str) -> Result<String, String> {
    let mut all_uses: BTreeSet<String> = BTreeSet::new();
    let mut aliases = String::new();
    let mut rows = String::new();
    for (i, spec) in specs.iter().enumerate() {
        let r = resolve(spec, reg)?;
        all_uses.extend(r.uses.iter().cloned());
        aliases.push_str(&format!(
            "    pub type S{i} = {ty};\n    pub fn s{i}(arr: &mut [usize]) {{ <S{i}>::sort(arr); }}\n",
            ty = r.type_expr,
        ));
        rows.push_str(&format!("        ({label:?}, s{i}),\n", label = r.label));
    }
    let uses: Vec<String> = all_uses.into_iter().collect();
    Ok(format!(
        "pub mod {module} {{\n    #[allow(unused_imports)] use super::*;\n{uses}\
         \x20   pub type SortFn = fn(&mut [usize]);\n{aliases}\
         \n    pub const SORTS: &[(&str, SortFn)] = &[\n{rows}    ];\n}}\n",
        uses = use_lines(&uses, "    "),
    ))
}

/// The REAL emit target: each solved sort → a self-contained module that
/// registers an `AlgorithmEntry` into the `ALGORITHMS` distributed slice — the
/// same shape `sort_registry_macro::sort_family!` produces today. Per-type
/// complexity is *inherited* from the type (`<Ty as HasTimeBounds>::WORST`,
/// etc.); `category`/`adaptive`/`max_input` come from the root component; the
/// category-specific `run_with_input`/battery bodies come from `emit_drivers`.
///
/// Emitted at the `include!` site's scope (each `mod __entry_N` does
/// `use super::*` so the catalog's `crate::…` `uses`-paths resolve). The caller
/// arranges for `linkme` + `ctor` to be in scope (faithful: real leaf crates
/// depend on both).
pub fn emit_entries(reg: &Registry, specs: &[SpecNode], cfg: &EmitConfig) -> Result<String, String> {
    let ctx = DriverCtx { abi: &cfg.abi };
    let abi = &cfg.abi;
    let mut out = String::from("// @generated by spec_core::emit_entries — do not edit\n");
    for (i, spec) in specs.iter().enumerate() {
        let r = resolve(spec, reg)?;
        let comp = reg
            .get(&spec.name)
            .ok_or_else(|| format!("unknown component `{}`", spec.name))?;
        let category = comp.category.clone().unwrap_or_else(|| "Sort".to_string());
        let code = driver(&category, &ctx)?;
        let max_input = match comp.max_input {
            Some(n) => format!("Some({n})"),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "#[allow(non_snake_case)]\n\
             mod __entry_{i} {{\n\
             \x20   #[allow(unused_imports)] use super::*;\n{uses}\
             \x20   pub type Ty = {ty};\n\
             \x20   fn run_default(input_name: &str, config: &{abi}::RunConfig, logger: &mut dyn {abi}::SortLogger<usize>) {{\n\
             \x20       {run_default}\n\
             \x20   }}\n\
             \x20   fn run_correct() {{\n\
             \x20       {run_correct}\n\
             \x20   }}\n\
             \x20   #[linkme::distributed_slice({abi}::ALGORITHMS)]\n\
             \x20   #[allow(non_upper_case_globals)]\n\
             \x20   static ENTRY: {abi}::AlgorithmEntry = {abi}::AlgorithmEntry {{\n\
             \x20       name: {label:?},\n\
             \x20       category: {abi}::Category::{cat},\n\
             \x20       worst: <Ty as {abi}::HasTimeBounds>::WORST,\n\
             \x20       best: <Ty as {abi}::HasTimeBounds>::BEST,\n\
             \x20       average: <Ty as {abi}::HasTimeBounds>::AVERAGE,\n\
             \x20       space: <Ty as {abi}::HasSpace>::SPACE,\n\
             \x20       stable: <Ty as {abi}::HasStability>::STABLE,\n\
             \x20       adaptive: {adaptive},\n\
             \x20       max_input_size: {max_input},\n\
             \x20       run_with_input: run_default,\n\
             \x20       run_correctness: run_correct,\n\
             \x20   }};\n\
             \x20   #[ctor::ctor]\n\
             \x20   #[allow(non_snake_case)]\n\
             \x20   fn register() {{ {abi}::register_sort_variant({label:?}, &[{menu:?}], &[]); }}\n\
             }}\n",
            uses = use_lines(&r.uses, "    "),
            ty = r.type_expr,
            label = r.label,
            cat = category,
            adaptive = comp.adaptive,
            run_default = code.run_default_body,
            run_correct = code.run_correct_body,
            menu = menu_root(&category),
        ));
    }
    Ok(out)
}

fn menu_root(category: &str) -> &'static str {
    match category {
        "Sort" => "sorts",
        "Partition" => "partitions",
        "Rotation" => "rotations",
        "Merge" => "merges",
        "SmallSort" => "small-sorts",
        "QuickSelect" => "quick-selects",
        _ => "other",
    }
}
