//! Build-time exercise of the combo_codegen trail rule.
//!
//! Reads this crate's own recursive component metadata, expands the
//! `Partition` role (which mutually recurses through `HeapBuild`), wraps
//! each concrete partition in `DemoSort<…>`, and emits the enumerated
//! variants. The expansion is bounded purely by the trail rule — without
//! it the `HeapExtract ↔ QuickBuild` cycle would never terminate.

use std::env;
use std::fmt::Write as _;
use std::path::PathBuf;

use combo_codegen::{expand_role, scan_manifest, ComponentRegistry, Family};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("Cargo.toml");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=build.rs");

    // Build a registry from this crate's metadata (reverse + add_front keeps
    // declaration order at the front of each role, matching the real wiring).
    let components = scan_manifest(&manifest).expect("trail_demo: scan_manifest failed");
    let mut registry = ComponentRegistry::default();
    for c in components.iter().rev() {
        registry.add_front_full(
            c.role.clone(),
            c.type_expr.clone(),
            c.label.clone(),
            c.uses.clone(),
            c.slots.clone(),
        );
        if let Some(n) = c.max_visits {
            let head = c.type_expr.split('<').next().unwrap_or(&c.type_expr).trim();
            registry.set_head_max_visits(head, n);
        }
    }

    // Trail-bounded recursive expansion of the cyclic role graph.
    let partitions = expand_role(&registry, "Partition");
    let family = Family::new("DemoSort<{P}>").axis("P", &partitions);
    let combos = family.combinations();

    let mut out = String::new();
    out.push_str("// @generated by trail_demo/build.rs — do not edit.\n\n");
    writeln!(out, "pub const COUNT: usize = {};", combos.len()).unwrap();

    out.push_str("\npub const VARIANT_TYPES: &[&str] = &[\n");
    for combo in &combos {
        writeln!(out, "    \"{}\",", combo.instantiated_type()).unwrap();
    }
    out.push_str("];\n");

    // Force every generated recursive type through the type-checker: if any
    // expansion produced an ill-formed type (bad bound, stray placeholder),
    // this module fails to compile.
    out.push_str("\n#[allow(dead_code)]\nmod _typecheck {\n    use super::*;\n");
    for (i, combo) in combos.iter().enumerate() {
        writeln!(out, "    pub type V{i} = {};", combo.instantiated_type()).unwrap();
    }
    out.push_str("}\n");

    std::fs::write(out_dir.join("trail_demo_variants.rs"), &out)
        .expect("trail_demo: failed to write generated variants");
}
