pub use crate::shell_branching::{
    BranchingStrategy, Classic, Fibonacci, LogParity, Optimised, Parity3, RootParity,
};

pub use crate::merge::{AuxMerge, InsertionMerge, RodMerge};

use sort_logger::SortLogger;
use array_vis_bench_core::bench_registry::correctness::SortFnPtr;

/// A runtime entry describing a concrete rod-sort variant.
///
/// Populated at link time via `#[linkme::distributed_slice(ROD_STRATEGIES)]`
/// entries generated by `register_rod!` below.
pub struct RodEntry {
    pub name: &'static str,
    pub big_o: &'static str,
    /// Navigation path for the tree menu, e.g. `["rod sorts", "classic", "insertion"]`.
    pub path: &'static [&'static str],
    pub sort_fn: SortFnPtr,
    pub sort_vis: fn(&mut [usize], &mut dyn SortLogger<usize>),
}

#[linkme::distributed_slice]
pub static ROD_STRATEGIES: [RodEntry] = [..];

// ---------------------------------------------------------------------------
// Registration macro
//
// Usage:  register_rod!(mod_name, StrategyType, MergeType)
//
// To add a new branching strategy or merge mode:
//   1. Add the impl to its home (utils/shell_branching/mod.rs for branching,
//      sorts/rod_sorts/merge.rs for merge).
//   2. For branching: also add it to the re-export list at the top of this
//      file. For merge: it's already re-exported via `merge::*`.
//   3. Call register_rod!(name, BranchingType, MergeType) below.
// ---------------------------------------------------------------------------
macro_rules! register_rod {
    ($mod:ident, $strat:ident, $merge:ident) => {
        // Gated OFF by default: the spec compiler (`spec_catalog`) emits the
        // canonical rod `ALGORITHMS` rows via the `RodSort<{strategy},{merge}>`
        // driver. Linking this crate's link-time `ALGO_ENTRY` / `ENTRY` items
        // too would double-register all 12 variants. Gating the whole generated
        // module removes every link-time + ctor-consumed item in one edit; the
        // types the spec needs (`RodSort`, the 6 strategies, the 2 merges) live
        // OUTSIDE this macro and stay available. See `[features]` in Cargo.toml.
        #[cfg(feature = "self_register")]
        mod $mod {
            use super::*;
            use crate::rod_sort::RodSort;
            use sort_logger::{NoOpLogger, SortLogger};

            const SORT_NAME: &str = const_format::concatcp!(
                "rod sort<strategy: ",
                $strat::NAME,
                ", merge: ",
                $merge::NAME,
                ">"
            );
            const PATH: &[&str] = &["rod sorts", $strat::NAME, $merge::NAME];

            fn sort_fn(arr: &mut [usize], logger: &mut NoOpLogger) { RodSort::<$strat, $merge>::sort(arr, logger) }
            fn sort_vis(arr: &mut [usize], logger: &mut dyn SortLogger<usize>) { RodSort::<$strat, $merge>::sort(arr, logger) }

            fn run_with_input(
                input_name: &str,
                config: &array_vis_bench_core::bench_registry::RunConfig,
                logger: &mut dyn SortLogger<usize>,
            ) {
                array_vis_bench_core::bench_registry::run_sort_with_input(input_name, config, sort_vis, logger);
            }

            fn run_correctness() {
                array_vis_bench_core::bench_registry::correctness::sort_battery(sort_fn, SORT_NAME);
                array_vis_bench_core::bench_registry::correctness::sort_stability_battery(sort_fn, SORT_NAME, false);
            }

            #[linkme::distributed_slice(ROD_STRATEGIES)]
            static ENTRY: RodEntry = RodEntry {
                name: SORT_NAME,
                big_o: $strat::BIG_O,
                path: PATH,
                sort_fn,
                sort_vis,
            };

            // Trait-derived: `RodSort::<Strategy, Merge>` declares its
            // own `HasTimeBounds`/`HasSpace`/`HasStability` based on the
            // merge variant (InsertionMerge → N²; AuxMerge → N log N).
            #[linkme::distributed_slice(array_vis_bench_core::bench_registry::ALGORITHMS)]
            static ALGO_ENTRY: array_vis_bench_core::bench_registry::AlgorithmEntry =
                array_vis_bench_core::bench_registry::AlgorithmEntry {
                    name: SORT_NAME,
                    category: array_vis_bench_core::bench_registry::Category::Sort,
                    worst: <RodSort<$strat, $merge> as array_vis_bench_traits::composable::HasTimeBounds>::WORST,
                    best: <RodSort<$strat, $merge> as array_vis_bench_traits::composable::HasTimeBounds>::BEST,
                    average: <RodSort<$strat, $merge> as array_vis_bench_traits::composable::HasTimeBounds>::AVERAGE,
                    space: <RodSort<$strat, $merge> as array_vis_bench_traits::composable::HasSpace>::SPACE,
                    stable: <RodSort<$strat, $merge> as array_vis_bench_traits::composable::HasStability>::STABLE,
                    adaptive: false,
                    max_input_size: None,
                    run_with_input,
                    run_correctness,
                };

            }
    };
}

// Cross-product: every branching strategy × every merge mode.
register_rod!(classic_insertion,     Classic,     InsertionMerge);
register_rod!(classic_aux,           Classic,     AuxMerge);
register_rod!(parity3_insertion,     Parity3,     InsertionMerge);
register_rod!(parity3_aux,           Parity3,     AuxMerge);
register_rod!(log_parity_insertion,  LogParity,   InsertionMerge);
register_rod!(log_parity_aux,        LogParity,   AuxMerge);
register_rod!(root_parity_insertion, RootParity,  InsertionMerge);
register_rod!(root_parity_aux,       RootParity,  AuxMerge);
register_rod!(optimised_insertion,   Optimised,   InsertionMerge);
register_rod!(optimised_aux,         Optimised,   AuxMerge);
register_rod!(fibonacci_insertion,   Fibonacci,   InsertionMerge);
register_rod!(fibonacci_aux,         Fibonacci,   AuxMerge);
