[workspace]
members = [
    ".",
    "sort_logger",
    "sort_vis",
    "sort_registry_core",
    "sort_registry_macro",
]
resolver = "2"

[package]
name = "array_vis_bench"
version = "0.1.0"
edition = "2021"
default-run = "array_vis_bench"

[lib]
name = "array_vis_bench"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
rand = "0.8"
lazy_static = "1.4.0"
rayon = "1.7"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sort_registry_macro = { path = "./sort_registry_macro" }
sort_registry_core = { path = "./sort_registry_core" }
ctor = "0.2"
linkme = "0.3"
const_format = "0.2"
sort_logger = { path = "./sort_logger" }
sort_vis = { path = "./sort_vis" }
#gif = "0.13.1"

## Benchmarks removed for now

[dev-dependencies]
