pub use crate::utils::shell_branching::{
    BranchingStrategy, Classic, Fibonacci, LogParity, Optimised, Parity3, RootParity,
};

pub use crate::sorts::rod_sorts::merge::{AuxMerge, InsertionMerge, RodMerge};

use crate::traits::log_traits::SortLogger;
use crate::traits::SortFn;

/// A runtime entry describing a concrete rod-sort variant.
///
/// Populated at link time via `#[linkme::distributed_slice(ROD_STRATEGIES)]`
/// entries generated by `register_rod!` below.
pub struct RodEntry {
    pub name: &'static str,
    pub big_o: &'static str,
    /// Navigation path for the tree menu, e.g. `["rod sorts", "classic", "insertion"]`.
    pub path: &'static [&'static str],
    pub sort_fn: SortFn,
    pub sort_vis: fn(&mut [usize], &mut dyn SortLogger<usize>),
}

#[linkme::distributed_slice]
pub static ROD_STRATEGIES: [RodEntry] = [..];

// ---------------------------------------------------------------------------
// Registration macro
//
// Usage:  register_rod!(mod_name, StrategyType, MergeType)
//
// To add a new branching strategy or merge mode:
//   1. Add the impl to its home (utils/shell_branching/mod.rs for branching,
//      sorts/rod_sorts/merge.rs for merge).
//   2. For branching: also add it to the re-export list at the top of this
//      file. For merge: it's already re-exported via `merge::*`.
//   3. Call register_rod!(name, BranchingType, MergeType) below.
// ---------------------------------------------------------------------------
macro_rules! register_rod {
    ($mod:ident, $strat:ident, $merge:ident) => {
        mod $mod {
            use super::*;
            use crate::sorts::rod_sorts::rod_sort::RodSort;
            use crate::traits::log_traits::{NoOpLogger, SortLogger};

            const SORT_NAME: &str = const_format::concatcp!(
                "rod sort<strategy: ",
                $strat::NAME,
                ", merge: ",
                $merge::NAME,
                ">"
            );
            const PATH: &[&str] = &["rod sorts", $strat::NAME, $merge::NAME];

            fn sort_fn(arr: &mut [usize], logger: &mut NoOpLogger) { RodSort::<$strat, $merge>::sort(arr, logger) }
            fn sort_vis(arr: &mut [usize], logger: &mut dyn SortLogger<usize>) { RodSort::<$strat, $merge>::sort(arr, logger) }

            fn run_with_input(
                input_name: &str,
                config: &crate::bench_registry::RunConfig,
                logger: &mut dyn SortLogger<usize>,
            ) {
                crate::bench_registry::run_sort_with_input(input_name, config, sort_vis, logger);
            }

            fn run_correctness() {
                crate::bench_registry::correctness::sort_battery(sort_fn, SORT_NAME);
                crate::bench_registry::correctness::sort_stability_battery(sort_fn, SORT_NAME, false);
            }

            #[linkme::distributed_slice(ROD_STRATEGIES)]
            static ENTRY: RodEntry = RodEntry {
                name: SORT_NAME,
                big_o: $strat::BIG_O,
                path: PATH,
                sort_fn,
                sort_vis,
            };

            #[linkme::distributed_slice(crate::bench_registry::ALGORITHMS)]
            static ALGO_ENTRY: crate::bench_registry::AlgorithmEntry =
                crate::bench_registry::AlgorithmEntry {
                    name: SORT_NAME,
                    category: crate::bench_registry::Category::Sort,
                    big_o: $strat::BIG_O,
                    stable: false,
                    max_input_size: None,
                    run_with_input,
                    run_correctness,
                };

            #[cfg(test)]
            mod sort_test {
                #[test]
                fn correctness() {
                    crate::bench_registry::test_helpers::check_sort_subprocess_assert(&super::ALGO_ENTRY, crate::bench_registry::test_helpers::DEFAULT_TIMEOUT);
                }
            }
        }
    };
}

// Cross-product: every branching strategy × every merge mode.
register_rod!(classic_insertion,     Classic,     InsertionMerge);
register_rod!(classic_aux,           Classic,     AuxMerge);
register_rod!(parity3_insertion,     Parity3,     InsertionMerge);
register_rod!(parity3_aux,           Parity3,     AuxMerge);
register_rod!(log_parity_insertion,  LogParity,   InsertionMerge);
register_rod!(log_parity_aux,        LogParity,   AuxMerge);
register_rod!(root_parity_insertion, RootParity,  InsertionMerge);
register_rod!(root_parity_aux,       RootParity,  AuxMerge);
register_rod!(optimised_insertion,   Optimised,   InsertionMerge);
register_rod!(optimised_aux,         Optimised,   AuxMerge);
register_rod!(fibonacci_insertion,   Fibonacci,   InsertionMerge);
register_rod!(fibonacci_aux,         Fibonacci,   AuxMerge);
