pub use crate::utils::shell_branching::{
    BranchingStrategy, Classic, Fibonacci, LogParity, Optimised, Parity3, RootParity,
};

use crate::traits::log_traits::SortLogger;
use crate::traits::SortFn;

/// A runtime entry describing a concrete rod-sort variant.
///
/// Populated at link time via `#[linkme::distributed_slice(ROD_STRATEGIES)]`
/// entries generated by `register_rod!` below.
pub struct RodEntry {
    pub name: &'static str,
    pub big_o: &'static str,
    /// Navigation path for the tree menu, e.g. `["rod sorts", "classic"]`.
    pub path: &'static [&'static str],
    pub sort_fn: SortFn,
    pub sort_vis: fn(&mut [usize], &mut dyn SortLogger<usize>),
}

#[linkme::distributed_slice]
pub static ROD_STRATEGIES: [RodEntry] = [..];

// ---------------------------------------------------------------------------
// Registration macro
//
// Usage:  register_rod!(mod_name, StrategyType)
//
// To add a new branching strategy:
//   1. Add the struct + BranchingStrategy impl to utils/shell_branching/mod.rs
//   2. Add it to the re-export list at the top of this file
//   3. Call register_rod!(name, Type) below — nothing else changes
// ---------------------------------------------------------------------------
macro_rules! register_rod {
    ($mod:ident, $strat:ident) => {
        mod $mod {
            use super::*;
            use crate::sorts::rod_sorts::rod_sort::RodSort;
            use crate::traits::log_traits::{NoOpLogger, SortLogger};

            const SORT_NAME: &str =
                const_format::concatcp!("rod sort<strategy: ", $strat::NAME, ">");
            const PATH: &[&str] = &["rod sorts", $strat::NAME];

            fn sort_fn(arr: &mut [usize], logger: &mut NoOpLogger) { RodSort::<$strat>::sort(arr, logger) }
            fn sort_vis(arr: &mut [usize], logger: &mut dyn SortLogger<usize>) { RodSort::<$strat>::sort(arr, logger) }

            fn run_with_input(
                input_name: &str,
                config: &crate::bench_registry::RunConfig,
                logger: &mut dyn SortLogger<usize>,
            ) {
                crate::bench_registry::run_sort_with_input(input_name, config, sort_vis, logger);
            }

            fn run_correctness() {
                crate::bench_registry::correctness::sort_battery(sort_fn, SORT_NAME);
                crate::bench_registry::correctness::sort_stability_battery(sort_fn, SORT_NAME, false);
            }

            #[linkme::distributed_slice(ROD_STRATEGIES)]
            static ENTRY: RodEntry = RodEntry {
                name: SORT_NAME,
                big_o: $strat::BIG_O,
                path: PATH,
                sort_fn,
                sort_vis,
            };

            #[linkme::distributed_slice(crate::bench_registry::ALGORITHMS)]
            static ALGO_ENTRY: crate::bench_registry::AlgorithmEntry =
                crate::bench_registry::AlgorithmEntry {
                    name: SORT_NAME,
                    category: crate::bench_registry::Category::Sort,
                    big_o: $strat::BIG_O,
                    stable: false,
                    max_input_size: None,
                    run_with_input,
                    run_correctness,
                };

            #[cfg(test)]
            mod sort_test {
                #[test]
                fn correctness() {
                    crate::bench_registry::test_helpers::check_sort_subprocess_assert(&super::ALGO_ENTRY, crate::bench_registry::test_helpers::DEFAULT_TIMEOUT);
                }
            }
        }
    };
}

register_rod!(classic,     Classic);
register_rod!(parity3,     Parity3);
register_rod!(log_parity,  LogParity);
register_rod!(root_parity, RootParity);
register_rod!(optimised,   Optimised);
register_rod!(fibonacci,   Fibonacci);
