// Pure branching strategy implementations live in utils::shell_branching.
// This module owns the registration infrastructure and re-exports the
// strategy types so the rest of shell_sorts can import from one place.
pub use crate::utils::shell_branching::{
    BranchingStrategy, Classic, Fibonacci, LogParity, Optimised, Parity3, RootParity,
};

use crate::traits::log_traits::SortLogger;
use crate::traits::SortFn;

/// A runtime entry describing a concrete shell-shell-sort variant.
///
/// Populated at link time via `#[linkme::distributed_slice(BRANCHING_STRATEGIES)]`
/// entries generated by `register_branching!` below.
pub struct BranchingEntry {
    pub name: &'static str,
    pub big_o: &'static str,
    /// Monomorphic sort for SORT_REGISTRY (NoOpLogger, fully inlinable).
    pub sort_fn: SortFn,
    /// Sort with dynamic logger dispatch, used by fn_sort for visualization.
    pub sort_vis: fn(&mut [usize], &mut dyn SortLogger<usize>),
}

#[linkme::distributed_slice]
pub static BRANCHING_STRATEGIES: [BranchingEntry] = [..];

// ---------------------------------------------------------------------------
// Registration macro
//
// Generates a private submodule with three concrete functions + two
// distributed-slice statics for a given BranchingStrategy type.
//
// Usage:  register_branching!(mod_name, StrategyType)
//
// To add a new branching strategy:
//   1. Add the struct + BranchingStrategy impl to utils/shell_branching/mod.rs
//   2. Add it to the re-export list at the top of this file
//   3. Call register_branching!(name, Type) below — nothing else changes
// ---------------------------------------------------------------------------
macro_rules! register_branching {
    ($mod:ident, $strat:ident) => {
        mod $mod {
            use crate::sorts::shell_sorts::branching::{
                BRANCHING_STRATEGIES, BranchingEntry, BranchingStrategy,
            };
            use crate::sorts::shell_sorts::shell_shell_sort::ShellShellSort;
            use crate::traits::log_traits::{NoOpLogger, SortLogger};
            use super::$strat;

            const SORT_NAME: &str =
                const_format::concatcp!("shell shell sort<strategy: ", $strat::NAME, ">");

            fn sort_fn(arr: &mut [usize], logger: &mut NoOpLogger) {
                ShellShellSort::<$strat>::sort(arr, logger);
            }
            fn sort_vis(arr: &mut [usize], logger: &mut dyn SortLogger<usize>) {
                ShellShellSort::<$strat>::sort(arr, logger);
            }
            fn bench(arr: &mut [usize]) {
                let mut l = NoOpLogger;
                ShellShellSort::<$strat>::sort(arr, &mut l);
            }

            #[linkme::distributed_slice(BRANCHING_STRATEGIES)]
            static ENTRY: BranchingEntry = BranchingEntry {
                name: SORT_NAME,
                big_o: $strat::BIG_O,
                sort_fn,
                sort_vis,
            };

            #[linkme::distributed_slice(crate::bench_registry::BENCH_SORTS)]
            static BENCH_ENTRY: crate::bench_registry::SortBenchEntry =
                crate::bench_registry::SortBenchEntry {
                    name: SORT_NAME,
                    big_o: $strat::BIG_O,
                    stable: false,
                    run: bench,
                };
        }
    };
}

register_branching!(classic,    Classic);
register_branching!(parity3,    Parity3);
register_branching!(log_parity, LogParity);
register_branching!(root_parity, RootParity);
register_branching!(optimised,  Optimised);
register_branching!(fibonacci,  Fibonacci);
