pub mod bad_heap_sort;
pub mod bad_heap_sort_alt;
pub mod comb_rec;
pub mod cyclent_sort;
pub mod cyclent_sort_stack;
pub mod cyclent_sort_stack_optimized;
pub mod quick_surrender;
pub mod quick_surrender_optimised;
pub mod slow_sort;
